---
- name: Clone Zenodo
  git:
    repo: 'https://github.com/zenodo/zenodo.git'
    dest: '{{ zenodo_install_path }}'
    version: master

- name: Build docker
  command: '{{ item }}'
  args:
    chdir: '{{ zenodo_install_path }}'
  with_items:
    - '{{ docker_compose_executable }} build'
    - '{{ docker_compose_executable }} up'

- name: Create the database, indexes, fixtures and an admin user
  command: '{{ item }}'
  with_items:
    - '{{ docker_compose_executable }} run --rm web bash /code/zenodo/scripts/init.sh'
    - '{{ docker_compose_executable }} run --rm statsd bash /init.sh'

- name: Load demo records
  command: '{{ item }}'
  with_items:
    - '{{ docker_compose_executable }} run --rm web zenodo fixtures loaddemorecords'
    - '{{ docker_compose_executable }} run --rm web zenodo migration recordsrun'
    - '{{ docker_compose_executable }} run --rm web zenodo index reindex --yes-i-know'
    - '{{ docker_compose_executable }} run --rm web zenodo index run -d'


